image: docker:latest

variables:
  IMAGE_NAME: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
  IMAGE_NAME_LATEST: "$CI_REGISTRY_IMAGE:latest"

stages:
 - package
 - deploy

workflow:
  rules:
    - if: $CI_COMMIT_TAG =~ /^release-?[0-9]+([.][0-9]+){2}$/
      variables:
        IMAGE_NAME: "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" 
    - if: $CI_COMMIT_BRANCH == "main"




release:
  stage: package
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull -t "$IMAGE_NAME" -t "$IMAGE_NAME_LATEST" -f Dockerfile .
    - docker push "$IMAGE_NAME"

deploy_stage:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
  image: lwolf/kubectl_deployer:latest
  environment:
    name: stage
    url: https://stage.clinops.app/
  before_script:
    - mkdir ~/.kube/
    - echo $KUBE_CONFIG_INTERNAL | base64 -d > config
    - mv config ~/.kube/
  script:
    - /bin/sh deploy.sh $IMAGE_NAME stage



